services:
  flask-app:
    image: fjiabinc/notdiamond2api
    ports:
      - "5007:3000"
    environment:
      - PORT=3000
      - AUTH_ENABLED=true
      - AUTH_TOKEN=your_token_here
    volumes:
      - ./accounts.txt:/app/accounts.txt:ro
      - ./workers.js:/app/workers.js:ro
